## Numpyの基礎
Numpyを扱うにあたって，基本的な操作事項，注意点をまとめた．

## Numpyの行列の作成
Numpyの行列は，`np.array()`を使って作成する．
多次元配列を作成することもできる．

In [7]:
import numpy as np
x = np.array([1,2])
print(x)
y =np.array([[51,55],[14,19],[0,4]])
print(y)

[1 2]
[[51 55]
 [14 19]
 [ 0  4]]


配列サイズを知りたい場合はshapeメソッドを使う．

In [10]:
print(x.shape)
print(y.shape)
print(np.array([[1],[2]]).shape)

(2,)
(3, 2)
(2, 1)


## numpyの演算
配列の演算は，要素ごとに行われる．特に掛け算の場合，内積ではなく，要素ごとの積になる点に留意する必要がある．


In [2]:
import numpy as np
x=np.array([1,2,3,4,5.0])
y=np.array([1,3,4,5,7])
print(x+y)
print(x-y)
print(x*y)
print(x/y)

[ 2.  5.  7.  9. 12.]
[ 0. -1. -1. -1. -2.]
[ 1.  6. 12. 20. 35.]
[1.         0.66666667 0.75       0.8        0.71428571]


また，配列が異なると(原則)エラーを返すが，配列とスカラーの演算は，スカラーを配列の各要素に適用したものとして扱われる．

エラー等も出ないので注意．

In [5]:
x = np.array([1,2])
print(x+1)#各要素に1を足す

print(x/2)# 各要素を2で割る

[2 3]
[0.5 1. ]


実は，配列と配列の演算においても，先ほどの行列とスカラーの演算と同じように，配列のサイズが異なる場合は，サイズが小さい方の配列を繰り返し適用することができる．(ブロードキャストという)

In [11]:
x = np.array([[1,2],[3,4]])
y = np.array([10,20])
print(x*y)

[[10 40]
 [30 80]]


上の例の場合は，xの各行において，[10,20]との間での各要素の積を計算する

具体的には

- [1,2]と[10,20]の間での各要素の積は[10,40]
- [3,4]と[10,20]の間での各要素の積は[30,80]
- これらがxの各行に対応する

今回は積の場合の例を示したが，その他の演算についても同様．例えば加算の場合以下の通り．

In [12]:
x = np.array([[1,2],[3,4]])
y = np.array([10,20])
print(x+y)

[[11 22]
 [13 24]]


## 配列のアクセス
配列のアクセスについては，通常のリストと同じように行うことが可能である．

In [14]:
x = np.array([0,1,2,3,4])
print(x[2])

2
